title: My test with Jeykll
description: Not that easy
theme: just-the-docs

url: https://jcctesolin.github.io/jtdocs.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
